apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertgeneration
  namespace: osa-suite
  labels:
    app: alertgeneration
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: alertgeneration
        track: stable
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
      containers:
      - name: alertgeneration
        image: rsiiris/{{IMAGE_URL}}
        ports:
        - containerPort: 6789
        volumeMounts:
        - name: systemconf
          mountPath: /tmp/common/config/config.properties
          subPath: config.properties
        - name: systemconf
          mountPath: /tmp/common/config/mq_ssl
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/America/New_York
      - name: systemconf
        configMap:
          name: systemconf
      imagePullSecrets:
      - name: dockerhubsecret
      dnsConfig:
        options:
        - name: single-request-reopen
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertgeneration
    track: stable
  name: alertgeneration
  namespace: osa-suite
  selfLink: /api/v1/namespaces/osa-suite/services/alertgeneration
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6789
  selector:
    app: alertgeneration
    track: stable
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
