apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: provisionservice
  namespace: osa-suite
  labels:
    app: provisionservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: provisionservice
        track: stable
    spec:
      dnsConfig:
        options:
          - name: single-request-reopen
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/America/New_York
      - name: systemconf
        configMap:
          name: systemconf
      - name: configkeystore
        emptyDir: {}
      containers:
      - name: provisionservice
        image: rsiiris/{{IMAGE_URL}}
        command: ["/bin/bash", "-c"] 
        args:
        - source /config/env.properties; 
          java 
           -Duser.timezone=America/New_York 
           -Dspring.datasource.jdbcUrl="jdbc:sqlserver://${MSSQLDBHOST}:${MSSQLDBPORT};database=${MSSQLOSADB}" 
           -Dspring.datasource.username=${MSSQLDBUSER} 
           -Dspring.datasource.encryptPassword=${MSSQLDBPASS} 
           -Dvertica.datasource.jdbcUrl="jdbc:vertica://${VERTICADBHOST}:${VERTICADBPORT}/FUSION" 
           -Dvertica.datasource.username=${VERTICADBUSER} 
           -Dvertica.datasource.encryptPassword=${VERTICADBPASS} 
           -Dvertica.common.schema=${VERTICADBSCHEMA} 
           -Dvertica.retailerschema.prefix=${VERTICADBRETAILERSCHEMAPREFIX}
           -Dserver.pmp.servername=${PMPSERVERNAME}
           -Dserver.pmp.tokenid=${PMPTOKENID}
           -Dserver.pmp.key=${PMPKEY}
           -jar provisionservice.jar;
        ports:
        - containerPort: 8282
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: systemconf
          mountPath: /config
        - name: configkeystore
          mountPath: /config/keystore
      initContainers:
      - name: initpod
        image: busybox
        command:
        - sh
        - /config/gen.sh
        volumeMounts:
        - name: systemconf
          mountPath: /config
        - name: configkeystore
          mountPath: /config/keystore            
      imagePullSecrets:
      - name: dockerhubsecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: provisionservice
    track: stable
  name: provisionservice
  namespace: osa-suite
  selfLink: /api/v1/namespaces/osa-suite/services/provisionservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8282
  selector:
    app: provisionservice
    track: stable
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
